# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        git submodule update --init --recursive
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python main.py
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: docs
        clean: true
