# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 7,19 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install loguru
        pip install requests
        python main.py
    - name: Deploy
      #uses: s0/git-publish-subdir-action@develop
      run: |
        git config --global user.email "2959435045@qq.com"
        git config --global user.name "Lition"
        git config --global github.user Lition
        git config --global github.token $GITHUB_TOKEN
        git remote add publish https://NilBridge:$GITHUB_TOKEN@github.com/NilBridge/nilbridge-module-center/.git
        git checkout --orphan publish
        git commit -m "Auto commit version $version"
        git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
        git push --force https://NilBridge:$GITHUB_TOKEN@github.com/NilBridge/nilbridge-module-center/.git /你的仓库名 /.git publish:gh-pages
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
